=== Multiscale-Genomics/VRE_tool_jsons/tool_specification/tool_schema_dev.json
{
  "id": "http://multiscalegenomics.eu/tool-schema",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "MuG tool definition schema",
  "description": "Specification of MuG tools as required for VRE",
  "properties": {
    "_id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "title": {
      "type": "string",
      "default": "null"
    },
    "short_description": {
      "type": "string",
      "default": "null"
    },
    "url": {
      "type": "string"
    },
    "publication": {
      "type": "string"
    },
    "owner": {
      "type": "object",
      "properties": {
        "institution": {
          "type": "string"
        },
        "author": {
          "type": "string"
        },
        "contact": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "user": {
          "type": "string"
        }
      },
      "id": "http://multiscalegenomics.eu/tool-schema/owner",
      "required": [
        "institution",
        "contact",
        "user"
      ]
    },
    "external": {
      "type": "boolean",
      "default": true
    },
    "infrastructure": {
      "type": "object",
      "properties": {
        "executable": {
          "type": "string"
        },
        "cpus": {
          "type": "integer",
          "default": 1
        },
        "memory": {
          "type": "string",
          "default": "1"
        },
        "wallTime": {
          "type": "integer",
          "default": 1440
        },
        "clouds": {
          "type": "object",
          "properties": {
            "mug-bsc": {
              "$ref": "#/definitions/cloud"
            },
            "mug-irb": {
              "$ref": "#/definitions/cloud"
            },
            "mug-ebi": {
              "$ref": "#/definitions/cloud"
            }
          },
          "additionalProperties": false
        }
      }
    },
    "has_custom_viewer": {
      "type": "boolean",
      "default": true
    },
    "keywords": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "protein",
          "dna",
          "rna",
          "visualizer",
          "3c",
          "chromatin",
          "interactions",
          "other"
        ]
      },
      "default": "other"
    },
    "input_files": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "help": {
            "type": "string",
            "default": null
          },
          "file_type": {
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
                "null",
                "FASTA",
                "FASTQ",
                "BAM",
                "BAI",
                "BED",
                "BB",
                "BEDGRAPH",
                "WIG",
                "BW",
                "GFF",
                "GFF3",
                "GTF",
                "TSV",
                "CSV",
                "TXT",
                "TAR",
                "TBI",
                "VCF",
                "JSON",
                "GEM",
                "BWT",
                "PDB",
                "XTC",
                "NETCDF",
                "DCD",
                "TOP",
                "TPR",
                "PARMTOP",
                "MDCRD",
                "RST",
                "CPT",
                "HDF5",
                "PDF",
                "TIFF",
                "LIF",
                "PNG"
              ]
            }
          },
          "data_type": {
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
                "sequence_genomic",
                "sequence_rna",
                "sequence_dna",
                "sequence_prot",
                "sequence_annotation",
                "sequence_mapping_index",
                "structure",
                "prot_dna_structure",
                "prot_structure",
                "na_structure",
                "na_traj",
                "na_traj_coords",
                "na_traj_top",
                "na_md_atom_traj_coords",
                "na_md_atom_traj_top",
                "na_md_cg_traj",
                "md_restart",
                "data_chip_seq",
                "data_atac_seq",
                "data_mnase_seq",
                "data_rna_seq",
                "data_dna_methylation",
                "data_fish",
                "hic_reads",
                "hic_sequences",
                "hic_contacts_matrix",
                "hic_contacts_coverage",
                "hic_tads_scale",
                "hic_contacts_peaks",
                "hic_contacts_differential",
                "hic_directionality",
                "chromatin_tads",
                "chromatin_traj",
                "chromatin_compartments",
                "chromatin_3dmodel_ensemble",
                "chromatin_3dmodel",
                "nucleosome_positioning",
                "nucleosome_dynamics",
                "nucleosome_gene_phasing",
                "tss_classification_by_nucleosomes",
                "nucleosome_free_regions",
                "nucleosome_stiffness",
                "docking_ranking",
                "prot_dna_specificity",
                "configuration_file",
                "tool_statistics",
                "tool_intermediate_file"
              ]
            }
          },
          "required": {
            "type": "boolean",
            "default": true
          },
          "allow_multiple": {
            "type": "boolean",
            "default": false
          }
        },
        "required": [
          "name",
          "description",
          "file_type",
          "data_type",
          "required",
          "allow_multiple"
        ]
      }
    },
    "arguments": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "help": {
            "type": "string",
            "default": null
          },
          "type": {
            "type": "string",
            "enum": [
              "integer",
              "number",
              "string",
              "enum",
              "enum_multiple",
              "boolean"
            ]
          },
          "default": {
            "type": "string",
            "default": "null"
          },
          "enum_items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "array"
              },
              "description": {
                "type": "array"
              }
            },
            "required": [
              "name"
            ]
          },
          "maximum": {
            "type": "integer"
          },
          "minimum": {
            "type": "integer"
          },
          "required": {
            "type": "boolean",
            "default": true
          },
          "allow_multiple": {
            "type": "boolean",
            "default": false
          }
        },
        "additionalProperties": false,
        "required": [
          "name",
          "description",
          "type"
        ]
      }
    },
    "control_file": {
      "type": "string",
      "default": "null"
    },
    "output_files": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "required": {
            "type": "boolean",
            "default": true
          },
          "allow_multiple": {
            "type": "boolean",
            "default": false
          },
          "file": {
            "type": "object",
            "properties": {
              "file_type": {
                "type": "string",
                "enum": [
                  "null",
                  "FASTA",
                  "FASTQ",
                  "BAM",
                  "BAI",
                  "BED",
                  "BB",
                  "BEDGRAPH",
                  "WIG",
                  "BW",
                  "GFF",
                  "GFF3",
                  "GTF",
                  "TSV",
                  "CSV",
                  "TXT",
                  "TAR",
                  "TBI",
                  "VCF",
                  "JSON",
                  "GEM",
                  "BWT",
                  "PDB",
                  "XTC",
                  "NETCDF",
                  "DCD",
                  "TOP",
                  "TPR",
                  "PARMTOP",
                  "MDCRD",
                  "RST",
                  "CPT",
                  "HDF5",
                  "PDF",
                  "TIFF",
                  "LIF",
                  "PNG"
                ]
              },
              "data_type": {
                "type": "string",
                "enum": [
                  "sequence_genomic",
                  "sequence_rna",
                  "sequence_dna",
                  "sequence_prot",
                  "sequence_annotation",
                  "sequence_mapping_index",
                  "structure",
                  "prot_dna_structure",
                  "prot_structure",
                  "na_structure",
                  "na_traj",
                  "na_traj_coords",
                  "na_traj_top",
                  "na_md_atom_traj_coords",
                  "na_md_atom_traj_top",
                  "na_md_cg_traj",
                  "md_restart",
                  "data_chip_seq",
                  "data_atac_seq",
                  "data_mnase_seq",
                  "data_rna_seq",
                  "data_dna_methylation",
                  "data_fish",
                  "hic_reads",
                  "hic_sequences",
                  "hic_contacts_matrix",
                  "hic_contacts_coverage",
                  "hic_tads_scale",
                  "hic_contacts_peaks",
                  "hic_contacts_differential",
                  "hic_directionality",
                  "chromatin_tads",
                  "chromatin_traj",
                  "chromatin_compartments",
                  "chromatin_3dmodel_ensemble",
                  "chromatin_3dmodel",
                  "nucleosome_positioning",
                  "nucleosome_dynamics",
                  "nucleosome_gene_phasing",
                  "tss_classification_by_nucleosomes",
                  "nucleosome_free_regions",
                  "nucleosome_stiffness",
                  "docking_ranking",
                  "prot_dna_specificity",
                  "configuration_file",
                  "tool_statistics",
                  "tool_intermediate_file"
                ]
              },
              "file_path": {
                "type": "string"
              },
              "compressed": {
                "type": "string",
                "enum": [
                  "null",
                  "gzip",
                  "zip"
                ]
              },
              "taxon_id": {
                "type": "integer"
              },
              "source_id": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "meta_data": {
                "type": "object",
                "properties": {
                  "description": {
                    "type": "string"
                  },
                  "tool": {
                    "type": "string"
                  },
                  "assembly": {
                    "type": "string"
                  },
                  "visible": {
                    "type": "boolean",
                    "default": true
                  }
                },
                "required": [
                  "description",
                  "tool",
                  "visible"
                ]
              }
            },
            "required": [
              "file_type",
              "data_type",
              "meta_data"
            ]
          }
        },
        "required": [
          "name",
          "required",
          "allow_multiple",
          "file"
        ]
      }
    }
  },
  "required": [
    "_id",
    "name",
    "title",
    "owner",
    "external",
    "keywords",
    "infrastructure",
    "input_files",
    "arguments",
    "output_files"
  ],
  "additionalProperties": false,
  "definitions": {
    "cloud": {
      "oneOf": [
        {
          "$ref": "#/definitions/SGE"
        },
        {
          "$ref": "#/definitions/PMES"
        }
      ]
    },
    "SGE": {
      "type": "object",
      "properties": {
        "launcher": {
          "type": "string",
          "pattern": "^SGE$"
        },
        "queue": {
          "type": "string",
          "default": "null"
        }
      },
      "required": [
        "launcher",
        "queue"
      ],
      "additionalProperties": true
    },
    "PMES": {
      "type": "object",
      "properties": {
        "launcher": {
          "type": "string",
          "pattern": "^PMES$"
        },
        "workflowType": {
          "type": "string",
          "enum": [
            "Single",
            "COMPSs"
          ],
          "default": "Single"
        },
        "imageName": {
          "type": "string"
        },
        "minimumVMs": {
          "type": "integer",
          "default":1
        },
        "initialVMs":{
          "type": "integer",
          "default":1
        }
      },
      "required": [
        "launcher",
        "imageName"
      ],
      "additionalProperties": true
    }
  }
}

=== Multiscale-Genomics/VRE_tool_jsons/tool_specification/examples/dev/pydockdna.json
{
    "_id": "pydockdna",
    "name": "pyDockDNA",
    "title": "Protein-DNA docking",
    "short_description": "PyDockDNA is a tool for the structural prediction of protein-DNA interactions",
    "owner": {
        "institution": "BSC",
        "author": "Brian Jiménez-García",
        "contact": "brian.jimenez@bsc.es",
        "url": "https://life.bsc.es/pid/pidweb/default/tools",
        "user": "bjimenez@bsc.es"
    },
    "external": true,
    "keywords": [
        "protein",
        "dna"
    ],
    "infrastructure": {
        "memory": "4.0",
        "cpus": 4,
        "executable": "/home/user/bin/mug/pydockdna",
        "clouds": {
            "mug-bsc": {
                "launcher": "PMES",
                "imageName": "uuid_pydockdna_51",
                "workflowType": "Single",
                "default_cloud": true
            },
            "mug-irb": {
                "launcher": "SGE",
                "queue": "pydock.q"
            }
        }
    },
    "input_files": [
        {
            "name": "receptor",
            "description": "Receptor PDB structure",
            "help": "PDB structure help",
            "file_type": [
                "PDB"
            ],
            "data_type": [
                "prot_structure"
            ],
            "required": true,
            "allow_multiple": false
        },
        {
            "name": "ligand",
            "description": "Ligand PDB structure",
            "help": "PDB structure help",
            "file_type": [
                "PDB"
            ],
            "data_type": [
                "na_structure",
                "prot_structure"
            ],
            "required": true,
            "allow_multiple": false
        }
    ],
    "arguments": [
        {
            "name": "scoring",
            "description": "Available energetic scoring functions",
            "help": "pyDockDNA is able to use different scoring functions in the step of re-scoring the generated docking poses",
            "type": "enum",
            "enum_items": {
                "description": [
                    "pyDock-DNA"
                ],
                "name": [
                    "pydockdna"
                ]
            },
            "required": true,
            "default": "PyDock DNA"
        },
        {
            "name": "models",
            "description": "Number of structures to model",
            "help": "The number of generated models by this tool",
            "type": "enum",
            "enum_items": {
                "name": [
                    "1",
                    "5",
                    "10",
                    "50"
                ]
            },
            "minimum": 1,
            "maximum": 50,
            "required": true,
            "default": "10"
        }
    ],
    "control_file": ".results.json",
    "output_files": [
        {
            "name": "energy_table",
            "required": true,
            "allow_multiple": false,
            "file": {
                "file_type": "CSV",
                "data_type": "docking_ranking",
                "compressed": "null",
                "meta_data": {
                    "description": "Ranking of docking poses",
                    "tool": "pydockdna",
                    "visible": true
                }
            }
        },
        {
            "name": "top_structures",
            "required": true,
            "allow_multiple": false,
            "file": {
                "file_type": "PDB",
                "data_type": "structure",
                "compressed": "null",
                "meta_data": {
                    "description": "Top 10 predictions",
                    "tool": "pydockdna",
                    "visible": true
                }
            }
        },
        {
            "name": "top10",
            "required": true,
            "allow_multiple": true,
            "file": {
                "file_type": "PDB",
                "data_type": "prot_dna_structure",
                "compressed": "null",
                "meta_data": {
                    "description": "Top10 predicted structures",
                    "tool": "pydockdna",
                    "visible": true
                }
            }
        },
        {
            "name": "results",
            "required": true,
            "allow_multiple": false,
            "file": {
                "file_type": "TAR",
                "data_type": "tool_statistics",
                "compressed": "gzip",
                "meta_data": {
                    "description": "Compressed results of the tool",
                    "tool": "pydockdna",
                    "visible": false
                }
            }
        }
    ]
}
